### ISSUE TITLE
Bug: Inconsistent Chart Curves

### ISSUE THREAD

**Issue by drewbotts** [Botts-Innovative-Research/oscar-viewer#113]
Need to sort out why the Event Details and Event Preview charts sometimes hide Gamma or Threshold curves

**Comment by kalynstricklin** [comment]
believe they just need an update called, adding in the yellow bar gives them an update and they seemed to be showing up. sometimes there is the case where it just does not graph the other one, clicking on another occupancy and coming back it would appear. im not sure if the curve layer just was not set before the chart was updated and so it did not attach or what. lmk if you have any other issues
