### ISSUE TITLE
BUG: Adjudication submit fails on Event Detail page

### ISSUE THREAD

**Issue by drewbotts** [Botts-Innovative-Research/oscar-viewer#139]
On the Event Detail pages, if you do not put a value in every field (other than notes) the adjudication will fail on submitting to the node. Several of these fields should be optional so they should have a "empty" value or state.

Vehicle ID -  should not be required - at some point default state should be occupancy FOI id 
Adjudicate - required for submit
Isotope - not required - default state is empty
Secondary Inspection - not required - default state should be "None"

**Comment by kalynstricklin** [comment]
i can do this one!
