### ISSUE TITLE
Lane Status Component

### ISSUE THREAD

**Issue by drewbotts** [Botts-Innovative-Research/oscar-viewer#7]
- List of lanes that are currently in an Alarm, Tamper, or Fault state
- When that state clears the lane is removed from the list 
- When a new lane enters one of those states it is placed at the top of the list
- When you click on the lane status it will take you to the live lane view of that lane

**Comment by kalynstricklin** [comment]
The lane status is completed to an extend. will need to do further testing when not hardcoding datasources. Tested lane status with two lanes running on the server to ensure messages were updating properly, and removing the correct statuses. The lane navigation will be modified to pass the necessary id's to render the lane when clicking the notifcation.
