### ISSUE TITLE
Lane View Table - All Occupancies, Alarms, Tamper and Faults

### ISSUE THREAD

**Issue by drewbotts** [Botts-Innovative-Research/oscar-viewer#74]
The Lane View Table should show all occupancies, alarms, tamper and fault events

**Comment by kalynstricklin** [comment]
added non alarming occupancies. unsure what you want to show for the alarms tampers faults. those currently show  in the lane status part of lane view

**Comment by drewbotts** [comment]
Good question, we will put this on the back burner until I have a good answer. This will probably move to the next phase
